version: '3'
services:
  frontend:
    image: mcreddi/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: mcreddi/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql

  mysql:
    image: mcreddi/mysql:v1
    container_name: mysql
    environment:
    volumes:
      - mysql:/var/lib/mysql

networks:
  expense:

volumes:
  mysql:
